#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /download
mkdir -p "/run/tomcat.8080"

# permissions
lsiown -R abc:abc \
    /config \
    /run/tomcat.8080

lsiown abc:abc \
    /download
