#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /download
mkdir -p "/run/tomcat.8080"

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    # permissions
    lsiown -R abc:abc \
        /config \
        /run/tomcat.8080

    lsiown abc:abc \
        /download
fi
